### ISSUE TITLE
NullPointer exception when ALICA is first run

### ISSUE THREAD

**Issue by kmdouglass** [LEB-EPFL/ALICA#15]
After the most recent changes to ALICA I'm getting the following error when using ALICA in Micro-Manager and testing it in virtual mode. It occurs only after I configure ALICA and run it for the very first time.

```
SEVERE: Could not dispatch event: org.micromanager.display.internal.CanvasUpdateQueue@6f0eccbd to public void org.micromanager.display.internal.CanvasUpdateQueue.onHistogramRequest(org.micromanager.display.internal.events.HistogramRequestEvent)
2017-12-07T14:07:20.138469 tid139993404663552 [IFO,App] Thread 35 (Thread-5) terminated with uncaught exception
2017-12-07T14:07:20.138498 tid139993404663552 [IFO,App] java.lang.NullPointerException
2017-12-07T14:07:20.138559 tid139993404663552 [IFO,App]   at org.micromanager.display.internal.inspector.MetadataPanel.imageChangedUpdate(MetadataPanel.java:289)
2017-12-07T14:07:20.138565 tid139993404663552 [IFO,App]   at org.micromanager.display.internal.inspector.MetadataPanel.updateMetadata(MetadataPanel.java:257)
2017-12-07T14:07:20.138569 tid139993404663552 [IFO,App]   at org.micromanager.display.internal.inspector.MetadataPanel.access$000(MetadataPanel.java:62)
2017-12-07T14:07:20.138572 tid139993404663552 [IFO,App]   at org.micromanager.display.internal.inspector.MetadataPanel$1.run(MetadataPanel.java:107)
2017-12-07T14:07:20.138576 tid139993404663552 [IFO,App]   at java.lang.Thread.run(Thread.java:748)
```

The problem is that the histogram display does not update and the Live preview won't appear unless I pause the Live feed and restart it. When the live preview is working, it shows that SpotCounter is finding the spots. I get the error with other analyzers as well, so it's probably a threading issue.

MM2 version: July 11, 2017 (built from source in Debian Jessie Linux)
ALICA commit: 083163

**Comment by kmdouglass** [comment]
I just tested the ALICA 0.2.4 release and it happens here as well.

**Comment by kmdouglass** [comment]
This is no longer reproducible on Micro-Manager 2.0gamma. Closing it for now...
