### ISSUE TITLE
Incorrect parameter description in Analyzer.processImage() javadocs

### ISSUE THREAD

**Issue by kmdouglass** [LEB-EPFL/ALICA#7]
**Note: this error occurs with ALICA v0.2.1, which is included with SASS. I need to test this with ALICA v0.2.4.**

The [Javadocs for the processImage() method](http://alica.readthedocs.io/en/latest/_javasphinx/ch/epfl/leb/alica/Analyzer.html#processimage) of the Analyzer interface states:

> **image** : image to be processed, you can either set it to an IJ.ImageProcessor using ImageProcessor.setPixels(image), or turn into 1D short array using (short[]) image

However, I get a casting error when I call this method from the AutoLase analyzer:

```java
Sourced file: inline evaluation of: ``import ij.IJ; import ch.epfl.leb.alica.analyzers.autolase.AutoLase;  // Creates  . . . '' : Method Invocation autolase.processImage : at Line: 21 : in file: inline evaluation of: ``import ij.IJ; import ch.epfl.leb.alica.analyzers.autolase.AutoLase;  // Creates  . . . '' : autolase .processImage ( sp , sp .getWidth ( ) , sp .getHeight ( ) , 0.1 , currSlice ) 

Target exception: java.lang.ClassCastException: ij.process.ShortProcessor cannot be cast to [S

	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:91)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:96)
	at bsh.BSHPrimaryExpression.eval(BSHPrimaryExpression.java:41)
	at bsh.BSHBlock.evalBlock(BSHBlock.java:125)
	at bsh.BSHBlock.eval(BSHBlock.java:75)
	at bsh.BSHBlock.eval(BSHBlock.java:41)
	at bsh.BSHForStatement.eval(BSHForStatement.java:105)
	at bsh.Interpreter.eval(Interpreter.java:659)
	at bsh.Interpreter.eval(Interpreter.java:750)
	at bsh.Interpreter.eval(Interpreter.java:739)
	at org.scijava.plugins.scripting.beanshell.BeanshellScriptEngine.eval(BeanshellScriptEngine.java:68)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:159)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:237)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: ij.process.ShortProcessor cannot be cast to [S
	at ij.process.ShortProcessor.setPixels(ShortProcessor.java:405)
	at ch.epfl.leb.alica.analyzers.autolase.AutoLase.processImage(AutoLase.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at bsh.Reflect.invokeMethod(Reflect.java:131)
	at bsh.Reflect.invokeObjectMethod(Reflect.java:77)
	at bsh.Name.invokeMethod(Name.java:852)
	at bsh.BSHMethodInvocation.eval(BSHMethodInvocation.java:69)
	... 19 more
```

Changing this argument from `sp` to `sp.pixels` in the BeanShell script below fixes the error. This implies that I cannot, in general, pass a SingleProcessor to this method as an argument.

```java
import ij.IJ;
import ch.epfl.leb.alica.analyzers.autolase.AutoLase;

// Creates the AutoLase instance
int threshold = 120;
AutoLase autolase = new AutoLase(threshold);

// Misc.
pixelSize = 0.1; // um

// Process the image
imp = IJ.getImage();
int stackSize = imp.nSlices;
print("There are " + stackSize + " images in this stack.");

for (int currSlice = 1; currSlice < 10; currSlice++) {
	imp.setSlice(currSlice);

	// Pass this directly to an analyzer's processImage method()
	sp = imp.getProcessor();
	autolase.processImage(sp, sp.getWidth(), sp.getHeight(), 0.1, currSlice);
	print(autolase.getIntermittentOutput());
}
```

**Comment by MStefko** [comment]
> This implies that I cannot, in general, pass a SingleProcessor to this method as an argument. 

[I assume you mean a ShortProcessor]

Indeed, the framework is not designed for this. The `Analyzer.processImage()` method is always expecting a "raw pixel data" object as first argument, not an `ImageProcessor`. Reason for this is that when you use ALICA in MicroManager (as is its primary purpose), in `AnalysisWorker.getNewImageFromCoreAndAnalyze()` we have:
```java
TaggedImage new_tagged_image = null;
Object new_image = null;
...
new_tagged_image = studio.core().getLastTaggedImage();
new_image = new_tagged_image.pix;
...
analyzer.processImage(new_image, (int) studio.core().getImageWidth(), (int) studio.core().getImageHeight(), studio.core().getPixelSizeUm(), image_acquisition_time);
```
This is a very speed-critical part of code, so I decided not to wrap the `new_image` object that contains raw pixel data into a `ShortProcessor` before passing it to the `Analyzer`. Instead, it is left up to the implementation of the `Analyzer` itself whether the wrapping in a `ImageProcessor` is necessary. For [AutoLase](https://github.com/LEB-EPFL/ALICA/blob/master/src/ch/epfl/leb/alica/analyzers/autolase/AutoLase.java), it was not originally done in Thomas' implementation because it worked with raw pixel data directly, however I later decided to use the `ShortProcessor` to fix the overflow bug. For [SpotCounter](https://github.com/LEB-EPFL/ALICA/blob/master/src/ch/epfl/leb/alica/analyzers/spotcounter/SpotCounter.java) we do wrap it in a `ShortProcessor` at line 75 because that is what Nico's algorithm used and it makes it more convenient.

The Javadoc is just information for the prospective new `Analyzer` developer, that the `image` object that is received from ALICA can be transformed into a more "useful" object, by either wrapping in a `ShortProcessor` or casting into a `short[]` array. I do agree that it could be more descriptive though.

**Comment by kmdouglass** [comment]
Perfect. Thanks for the description!

I'll change the Javadocs shortly to make this more clear.

**Comment by kmdouglass** [comment]
Fixed and on master.
